# Generated by Django 5.0.4 on 2024-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tk_im',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('refTaskId', models.IntegerField(blank=True, null=True)),
                ('shopId', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('complatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tk_im',
            },
        ),
    ]
