# Generated by Django 5.0.4 on 2024-05-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tk_im'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tk_im',
            old_name='complatedAt',
            new_name='complateAt',
        ),
        migrations.RenameField(
            model_name='tk_im',
            old_name='refTaskId',
            new_name='refTaskid',
        ),
    ]
