# Generated by Django 5.0.4 on 2024-05-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_complatedat_tk_im_complateat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_im',
            name='taskId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
