# Generated by Django 5.0.4 on 2024-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_tk_im_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_im',
            name='complateAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tk_im',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tk_im',
            name='taskId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tk_im',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
