# Generated by Django 5.0.4 on 2024-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_tk_im_complateat_alter_tk_im_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_im',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tk_im',
            name='refTaskid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tk_im',
            name='shopId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
