# Generated by Django 5.0.4 on 2024-05-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tk_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
