# Generated by Django 5.0.4 on 2024-05-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_tk_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tk_information',
            table='tk_information',
        ),
    ]
