# Generated by Django 5.0.4 on 2024-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_tk_information_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_information',
            name='content',
            field=models.TextField(),
        ),
    ]
