# Generated by Django 5.0.4 on 2024-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_tk_information_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'creators',
            },
        ),
    ]
