# Generated by Django 5.0.4 on 2024-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_creators'),
    ]

    operations = [
        migrations.CreateModel(
            name='tkuser_im',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('taskId', models.CharField(max_length=255)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(max_length=20)),
                ('refTaskid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('sendAt', models.DateTimeField(blank=True, null=True)),
                ('complateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tkuser_im',
            },
        ),
    ]
