# Generated by Django 5.0.4 on 2024-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_tkuser_im'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tk_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tk_chat',
            },
        ),
        migrations.CreateModel(
            name='Tk_invacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('taskId', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=20)),
                ('refTaskid', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.CharField(blank=True, max_length=255, null=True)),
                ('dialogId', models.CharField(blank=True, max_length=255, null=True)),
                ('shopId', models.CharField(blank=True, max_length=255, null=True)),
                ('productId', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('complateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tk_invacation',
            },
        ),
        migrations.RemoveField(
            model_name='tkuser_im',
            name='userId',
        ),
        migrations.AddField(
            model_name='tk_im',
            name='dialogId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tkuser_im',
            name='dialogId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
