# Generated by Django 5.0.4 on 2024-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_tk_chat_tk_invacation_remove_tkuser_im_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_chat',
            name='sendTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
