# Generated by Django 5.0.4 on 2024-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_tk_chat_sendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkuser_im',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
