# Generated by Django 5.0.4 on 2024-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_tkuser_im_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_invacation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
