# Generated by Django 5.0.4 on 2024-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_tk_invacation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_chat',
            name='isAgree_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
