# Generated by Django 5.0.4 on 2024-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_tk_chat_isagree_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkuser_im',
            name='receivestatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
