# Generated by Django 5.0.4 on 2024-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_tkuser_im_receivestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk_chat',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
