# Generated by Django 4.2.14 on 2024-08-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_tk_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_invacation',
            name='receivestatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
