# Generated by Django 4.2.14 on 2024-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_tk_im_checkedat_tk_im_receivestatus_tk_im_sendat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_invacation',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
