# Generated by Django 4.2.14 on 2024-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_tk_invacation_delivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creators',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
