# Generated by Django 4.2.14 on 2024-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_creators_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_invitations',
            field=models.IntegerField(null=True),
        ),
    ]
