# Generated by Django 4.2.14 on 2024-08-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('task', '0024_task_total_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpa_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=50)),
                ('has_requested', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'rpa_key',
            },
        ),
    ]
