# Generated by Django 4.2.14 on 2024-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_creators_is_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='filter_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
