# Generated by Django 5.0.4 on 2024-05-21 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_category1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'base_category1',
            },
        ),
        migrations.CreateModel(
            name='base_category2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.base_category1')),
            ],
            options={
                'db_table': 'base_category2',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hasFreeSample', models.BooleanField(default=False)),
                ('commissionRate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('CooperationFee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_link', models.TextField()),
                ('match_tag', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('base_category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.base_category2')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'db_table': 'tk_goods',
            },
        ),
    ]
