# Generated by Django 5.0.4 on 2024-05-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
