# Generated by Django 5.0.4 on 2024-05-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidsysRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('requirement', models.TextField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('shop_info', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tk_raidsys_rule',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='product_status',
            field=models.BooleanField(choices=[(False, '未建联'), (True, '已经建联')], default=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='raidsysrule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.raidsysrule'),
        ),
    ]
