# Generated by Django 5.0.4 on 2024-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='CooperationFee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='commissionRate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='hasFreeSample',
            field=models.BooleanField(default=False),
        ),
    ]
