# Generated by Django 5.0.4 on 2024-05-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_raidsysrule_goods_product_status_goods_raidsysrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidsysrule',
            old_name='shop_indo',
            new_name='shop_info',
        ),
    ]
