# Generated by Django 4.2.14 on 2024-09-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_goods_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='id',
            new_name='product_id',
        ),
    ]
