# Generated by Django 5.0.4 on 2024-05-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_indo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('payment_way', models.CharField(max_length=100)),
                ('order_comment', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_indo', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Order Indo',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='payment.order_indo')),
            ],
            options={
                'verbose_name_plural': 'Order Detail',
            },
        ),
        migrations.CreateModel(
            name='order_status_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100)),
                ('operate_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_log', to='payment.order_indo')),
            ],
            options={
                'verbose_name_plural': 'Order Status Log',
            },
        ),
        migrations.CreateModel(
            name='payment_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_way', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('callback', models.CharField(max_length=100)),
                ('callback_code', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='payment.order_indo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Payment Info',
            },
        ),
    ]
