# Generated by Django 5.0.4 on 2024-05-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='create_at',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='update_at',
            new_name='updateAt',
        ),
    ]
