# Generated by Django 5.0.4 on 2024-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
